spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/examsystem
    username: root
    password: MYSQL123
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB
  application:
    name: exam-system

server:
  port: 80