spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/examsystem
    username: root
    password: MYSQL123
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 127.0.0.1
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB
  application:
    name: exam-system
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
  mvc:
    static-path-pattern: /static/**

server:
  port: 80